# Auswertung Zelasto Studie

![Bild Depth Touch](images/depth-touch.jpg)

Jupyter Notebook um die in der Zelasto Studie geschriebenen CSV Dateien auf und auszuwerten. 

1. [Studienablauf](#Studienablauf)
1. [Aktuelle Lösung](Aktuelle-Lösung)
1. [Struktur Logfiles](#Struktur-Logfiles)
1. [Werte im Logfile](#Werte-im-Logfile)
1. [Statusabfolge](#Statusabfolge)
1. [Definition der Tiefenebenen](#Definition-der-Tiefenebenen)

## Studienablauf
---

* 6 Probe-Aufgaben (TASK) mit jeweils 2 Wiederholungen (TRIAL)
* 3 Blöcke (BLOCK) mit jeweils
    * 18 Aufgaben (TASK) mit jeweils 5 Wiederholungen (TRIAL)
    * In dem Block wurde immer eine Mapping-Methode (MAPPING_METHOD) genutzt
        * `direct / densening / widening`
    * Variiert wurden in den Aufgaben (TASK) die Anzahl der Tiefenebenen:
        * `6 / 9 / 12 / 15 / 18 / 21`
    * Variiert in den Wiederholungen (TRIALS) wurden die Zielebenen (random)
* Zuordnung Ebene <-> MAPPING_METHOD <-> Tiefe in eigener csv (depthlayers.csv)
* Erfolgs-/Fehlermöglichkeiten:
    * `COMPLETED / FAILED / TERMINATED`

## Aktuelle Lösung
---

* Iterativer / objektorientierter Ansatz (nicht wirklich Data Science strukturiert)
* Gesucht: besser anpassbare, „einfache“ data science Lösung

## Struktur Logfiles
---

`2021-05-11T14:55:08.419Z; INTERACTION; direct;18;14,9,5,1,17;18;1; 0.5099127;0.5482645;-0.449999869;637563489084131200;1;8`

| DateTime (LogServer)     | STATE          | mapping method | Task-No. | Target Layers | Layer-Count | Trial-Idx | PosX             | PosY                                                  | PosZ         | TimeStamp (Server) | InteractionType | CurrentLayer |
| ------------------------ | -------------- | -------------- | -------- | ------------- | ----------- | --------- | ---------------- | ----------------------------------------------------- | ------------ | ------------------ | --------------- | ------------ |
| 2021-05-11T14:55:08.419Z | INTERACTION    | direct         | 18       | 14,9,5,1,17   | 18          | 1         | 0.5099127        | 0.5482645                                             | -0.449999869 | 637563489084131200 | 1               | 8            |
| 2021-05-10T12:14:37.259Z | VIEW           | direct         | 2        | 7,8,1,5,2     | 9           | 0         | TASK_DESCRIPTION |                                                       |              |                    |                 |              |
| 2021-05-10T12:14:37.259Z | TASK           | direct         | 2        | 7,8,1,5,2     | 9           | 0         |                  |                                                       |              |                    |                 |              |
| 2021-05-10T12:13:51.730Z | MAPPING_METHOD | direct         | 1        | 4,5,3,1,2     | 6           | 0         |                  |                                                       |              |                    |                 |              |
| 2021-05-10T12:14:37.264Z | SUBTASK        | direct         | 2        | 7,8,1,5,2     | 9           | 0         | 2                |                                                       |              |                    |                 |              |
| 2021-05-10T12:14:37.265Z | SUBTASK_STATE  | direct         | 2        | 7,8,1,5,2     | 9           | 0         | START            |                                                       |              |                    |                 |              |
| 2021-05-10T12:14:39.587Z | VIEW           | direct         | 2        | 7,8,1,5,2     | 9           | 0         | TASK_VIEW        |                                                       |              |                    |                 |              |
| 2021-05-10T12:14:45.064Z | SUBTASK_STATE  | direct         | 2        | 7,8,1,5,2     | 9           | 0         | HOLD             |                                                       |              |                    |                 |              |
| 2021-05-10T12:14:46.565Z | SUBTASK_STATE  | direct         | 2        | 7,8,1,5,2     | 9           | 0         | COMPLETED        |                                                       |              |                    |                 |              |
| 2021-05-10T12:10:39.115Z | SUBTASK_STATE  | direct         | 1        | 1,5           | 6           | 0         | FAILED           | wrong level approved                                  |              |                    |                 |              |
| 2021-05-10T12:13:38.243Z | SUBTASK_STATE  | densening      | 6        | 3,12          | 14          | 0         | TERMINATED       | switched to other level before hold timeout completed |              |                    |                 |              |

## Werte im Logfile
---

* Tasks:
    * 1-6 (Test)
    * 1-18 (Block 1)
    * 19-36 (Block 2)
    * 37 - 54 (Block 3)

* 3 Blocks for any mapping method

* STATE:
  
    | State Value        | Description                                       | SubTypes           |
    | ------------------ | ------------------------------------------------- | ------------------ |
    | __INTERACTION__    | Trial interaction                                 | -                  |
    | __VIEW__           | switched view (describe Task)                     | TASK_VIEW          |
    |                    | switched view in test runs (describe Task)        | Test Run TASK_VIEW |
    |                    |                                                   | TASK_DESCRIPTION   |
    | __TASK__           |                                                   |                    |
    | __MAPPING_METHOD__ | starting to next large block (mapping method)     |                    |
    | __SUBTASK__        | same as the next: starting to next task           |                    |
    | __SUBTASK_STATE__  | start of the trial after Subtask                  | START              |
    |                    | dwell time in a layer exceeded: hold-timer starts | HOLD               |
    |                    | end of the trial (Success)                        | COMPLETED          |
    |                    | end of the trial (hold failure                    | TERMINATED         |
    |                    | end of the trial (wrong level ?)                  | FAILED             |

* mapping method - describes, how layers are aligned:
    * __direct__ (equivalent distance)
    * __densening__ (larger distance on top, decreasing with depth value)
    * __widening__ (narrower distance on top, increasing with depth value)

* Task-No.
    * running number of tasks

* Target Layers, Trial-Idx
    * array of targets for each layer in current Task
    * trial-Index (zero based) describes target layer for current trial

* Layer-Count
    * number of max layers in Task

* PosX, PosY, PosZ
    * Positions received from Tracking Server
    * PosX / PosY in range [0, 1]
    * PosZ in range [-1, 1] with 0 = on the surface / no interaction, -1 max push, +1 max pull

* Timestamp (Server)
    * timestamp received from Tracking server: miliseconds based unix time stamp

* InteractionType
    * type recognized from server (1 = PUSH)

* current layer
    * layer associated with received depth value

## Statusabfolge
---

1. START (missing on first trial !) OR
    * start of an new task
2. TASK_VIEW / TASK_DESCRIPTION
3. HOLD
4. COMPLETED / TERMINATED / FAILED
   

## Definition der Tiefenebenen
---

__Location:__ `data/depthlayers.csv` [File](data/depthlayers.csv)

`6; direct; 0 | 1 | 2 | 3 | 4 | 5 | 6; 0 | 0.0834 | 0.25 | 0.4167 | 0.5834 | 0.75 | 0.9167 | 1`

| NUM_LAYERS       | MAPPING_METHOD            | DEPTH_LAYER_ID                         | DEPTH_LAYER_BORDER              |
| ---------------- | ------------------------- | -------------------------------------- | ------------------------------- |
| number of layers | mapping method for  block | idx of the depth layer in border array | start depths for each layer idx |

* mapping of layers to depth ranges for better evaluation how "good" a depth layer has been hit

## Aufgaben
---

### Vorverarbeitung - Cleaning

* Probe-Aufgaben und eigentliche Studie in verschiedene Dateien
* Ersetzen: Pro Task, muss im ersten Trial  TASK_VIEW mit START getauscht werden
* Spalten benennen (für bessere Adressierung)
* Nebenbedingung/Bonus: sowohl „nur Studie“ / „nur Test“ / „Test und Studie“ zusammen laden  Ordner-Struktur / Namensschema ?
* Lösung/Code dokumentieren (jupyter notebook)

In [1]:
# csv Dateien sind im Verzeichnis ../data zu finden

import pandas as pd
import glob
import os

export = "../export/"

path = "../data/"
all_files = glob.glob(path + "/*.csv")

# for debugging: only use first file
# all_files = all_files[9:11]

study = []
cleanedStudy = []
columnNames =["DateTime", "State", "mappingMethod", "TaskNo", "TargetLayers", "LayerCount", "TrialIdx", "posX", "posY", "posZ", "TimeStamp", "iteractionType", "currentLayer"]

totalLength = 0

for filename in all_files:
    df = pd.read_csv(filename, sep=";", names = columnNames)
    fn = os.path.basename(filename).split(".")[0]    
    df["Proband"] = fn
    study.append(df)
    totalLength += len(df)
    
print("totallines: " + str(totalLength))

data_complete = pd.concat(study, ignore_index=True)
display (data_complete)

currentLine = 0
swaps = 0

marker = []
marker.append(["Id", "EndInit", "EndTests", "SwapLines"])

for testData in study:   
    currentLine += len(testData)
    
    # compare taskNo of next row by shifting series    
    testData["shifted"] = testData["TaskNo"].shift(-1)
    
    # find elements where the taskNo of the next row is 1 and the current row is larger than 1 (that is where the learning tasks end / the whole test restarts )
    markers = testData[(testData["shifted"] == 1) & (testData["TaskNo"] > 1)]
    
    # assert that there are always exactly 2 markers 
    if len(markers) != 2:
        raise Exception("invalid number of markers")
        
    start = markers.index[0]+1
    end = markers.index[1]+1
        
    filteredData = testData.drop(testData.index[end:len(testData)])     
    filteredData = filteredData.drop(filteredData.index[0:start])
    
    filteredData.reset_index(drop=True, inplace=True)
    
    # display(filteredData)
    
    marker.append([testData["Proband"][0], start, end, "-"])    
    
    print("Processed: " + str(currentLine) + " of " +  str(totalLength) + "(" + str(testData["Proband"][0]) + ")")      

    # exchange TASK_VIEW ans START in the first Trial for each Task
   
    startLine = filteredData[(filteredData["TrialIdx"] == 0) & (filteredData["posX"] == " START")]
    taskLine= filteredData[(filteredData["TrialIdx"] == 0) & (filteredData["posX"] == " TASK_VIEW")]
    
    # iterate over task lines (start/task swpa is not necessary every time) to find START and TASK_VIEW 
    # Swap lines when TASK_VIEW was found
    for i in range(0, len(taskLine)):
        linecopy = filteredData.iloc[startLine.index[i]]
        filteredData.iloc[startLine.index[i]] = filteredData.iloc[taskLine.index[i]]
        filteredData.iloc[taskLine.index[i]] = linecopy
        
        marker.append([testData["Proband"][0], "-", "-", str(startLine.index[i] + end) + " <-> " + str(taskLine.index[i] + end)]);

    cleanedStudy.append(filteredData)
    
markerframe = pd.DataFrame(data=marker)
markerframe.to_csv(rf'{export}marker.csv', sep= ";")
    
print('finished')

df_cleanedStudy = pd.concat(cleanedStudy)
df_cleanedStudy.to_csv(rf'{export}cleanedStudy.csv', sep= ";")

totallines: 2733080

,DateTime,State,mappingMethod,TaskNo,TargetLayers,LayerCount,TrialIdx,posX,posY,posZ,TimeStamp,iteractionType,currentLayer,Proband
0,2021-05-10T12:08:25.383Z,INTERACTION,direct,1,"1,5",6,0,-,-,-,-,-,-,01
1,2021-05-10T12:08:25.414Z,INTERACTION,direct,1,"1,5",6,0,-,-,-,-,-,-,01
2,2021-05-10T12:08:25.446Z,INTERACTION,direct,1,"1,5",6,0,-,-,-,-,-,-,01
3,2021-05-10T12:08:25.475Z,INTERACTION,direct,1,"1,5",6,0,-,-,-,-,-,-,01
4,2021-05-10T12:08:25.521Z,INTERACTION,direct,1,"1,5",6,0,-,-,-,-,-,-,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2733075,2021-06-30T12:37:47.525Z,INTERACTION,densening,1,"8,2,7,1,5",9,0,-,-,-,-,-,-,24
2733076,2021-06-30T12:37:47.564Z,INTERACTION,densening,1,"8,2,7,1,5",9,0,-,-,-,-,-,-,24
2733077,2021-06-30T12:37:47.596Z,INTERACTION,densening,1,"8,2,7,1,5",9,0,-,-,-,-,-,-,24
2733078,2021-06-30T12:37:47.639Z,INTERACTION,densening,1,"8,2,7,1,5",9,0,-,-,-,-,-,-,24
2733079,2021-06-30T12:37:47.678Z,INTERACTION,densening,1,"8,2,7,1,5",9,0,-,-,-,-,-,-,24

Processed: 86106 of 2733080(01)
Processed: 227176 of 2733080(02)
Processed: 339055 of 2733080(03)
Processed: 478493 of 2733080(04)
Processed: 594798 of 2733080(05)
Processed: 720103 of 2733080(06)
Processed: 883086 of 2733080(07)
Processed: 1064088 of 2733080(08)
Processed: 1184333 of 2733080(09)
Processed: 1299948 of 2733080(10)
Processed: 1391165 of 2733080(11)
Processed: 1490464 of 2733080(12)
Processed: 1674368 of 2733080(13)
Processed: 1777237 of 2733080(14)
Processed: 1904586 of 2733080(15)
Processed: 2014642 of 2733080(16)
Processed: 2120240 of 2733080(17)
Processed: 2227439 of 2733080(18)
Processed: 2343047 of 2733080(19)
Processed: 2444664 of 2733080(20)
Processed: 2543798 of 2733080(22)
Processed: 2634877 of 2733080(23)
Processed: 2733080 of 2733080(24)
finished

---

### Extraktion

#### Erfolg/Fehler für jeden Trial und je Proband

| PROBAND | BLOCK | TASK | TRIAL | MAPPING_METHOD | NUM_LAYERS | TARGET | TARGET_RELATIVE | RESULT    |
| ------- | ----- | ---- | ----- | -------------- | ---------- | ------ | --------------- | --------- |
| 1       | 1     | 2    | 5     | direct         | 15         | 7      | 0.46666         | COMPLETED |
| .       | .     | .    | .     | .              | .          | .      | .               | .         |
| .       | .     | .    | .     | .              | .          | .      | .               | .         |

---

In [2]:
import numpy as np
#create new Dataframe for the results per Trial and Proband
# cn_result = ["Proband", "Block", "Task", "Trial", "MappingMethod", "NumLayers", "Target", "Target_Relative", "Result", "Result_Numeric", "FrameNumber_Start", "FrameNumber_Finish"]

probands = []

for proband in cleanedStudy:

    start = proband[(proband['posX']  == " START")]
    # remove duplicate labels (keep last)
    start = start.drop_duplicates(['TaskNo', 'TrialIdx'], keep='last')
    
    finish = proband[(proband["posX"] == " COMPLETED") | (proband["posX"] == " FAILED") | (proband["posX"] == " TERMINATED")]
    
    # remove duplicate labels (keep first)
    finish = finish.drop_duplicates(['TaskNo', 'TrialIdx'])
    
    # setting the indices - associate the date sets with each other - nth start <-> nth finish 
    finish["FrameNumber_Start"] = start.index
    start["FrameNumber_Finish"] = finish.index
    
    finish = finish.reset_index()
    start = start.reset_index()
    
    result = pd.DataFrame(start["mappingMethod"])
    result = result.rename(columns= {"mappingMethod": "MappingMethod"})
    
    result["FrameNumber_Start"] = finish["FrameNumber_Start"]
    result["FrameNumber_Finish"] = start["FrameNumber_Finish"]
    result["Block"] = (start["TaskNo"] / 18).apply(np.ceil).astype(int)
    result["Task"] = (start["TaskNo"] - ((result["Block"] - 1) * 18)).astype(int)
    result["Trial"] = start["TrialIdx"].astype(int)
    result["NumLayers"] = start["LayerCount"]    
    result["Target"] = start["TargetLayers"].str.split(",")
    result["Target"] = result.apply(lambda item: item["Target"][item["Trial"]], axis = 1).astype(int)
    result["Target_Relative"] = result["Target"].astype(float) / result["NumLayers"].astype(float)

    result["Result"] = finish["posX"]
    result["Result_Numeric_Completed"] = result["Result"].map({" COMPLETED": 1, " FAILED": 0, " TERMINATED": 0})
    result["Result_Numeric_Terminated"] = result["Result"].map({" COMPLETED": 0, " FAILED": 0, " TERMINATED": 1})
    result["Result_Numeric_Failed"] = result["Result"].map({" COMPLETED": 0, " FAILED": 1, " TERMINATED": 0})
    
    result["Proband"] = start["Proband"]
    
    probands.append(result)

allResults = pd.concat(probands, ignore_index=True)
display(allResults)

allResults.to_csv(rf'{export}results.csv', sep= ";")

,MappingMethod,FrameNumber_Start,FrameNumber_Finish,Block,Task,Trial,NumLayers,Target,Target_Relative,Result,Result_Numeric_Completed,Result_Numeric_Terminated,Result_Numeric_Failed,Proband
0,direct,135,330,1,1,0,6,4,0.666667,COMPLETED,1,0,0,01
1,direct,413,531,1,1,1,6,5,0.833333,TERMINATED,0,1,0,01
2,direct,603,804,1,1,2,6,3,0.500000,COMPLETED,1,0,0,01
3,direct,870,969,1,1,3,6,1,0.166667,TERMINATED,0,1,0,01
4,direct,1029,1177,1,1,4,6,2,0.333333,COMPLETED,1,0,0,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6205,widening,89346,89495,3,18,0,6,4,0.666667,COMPLETED,1,0,0,24
6206,widening,89542,89684,3,18,1,6,5,0.833333,COMPLETED,1,0,0,24
6207,widening,89739,89833,3,18,2,6,2,0.333333,TERMINATED,0,1,0,24
6208,widening,89887,90030,3,18,3,6,3,0.500000,COMPLETED,1,0,0,24
6209,widening,90074,90208,3,18,4,6,1,0.166667,FAILED,0,0,1,24

---
#### Versuchsdauer für jeden Trial und je Proband

| PROBAND | BLOCK | TASK | TRIAL | MAPPING_METHOD | NUM_LAYERS | TARGET | DURATION |
| ------- | ----- | ---- | ----- | -------------- | ---------- | ------ | ------   |
| 1       | 1     | 2    | 5     | direct         | 15         | 7      | 15.532s  |
| .       | .     | .    | .     | .              | .          | .      | .        |
| .       | .     | .    | .     | .              | .          | .      | .        |

---

In [3]:
#create new Dataframe for the results per Trial and Proband
# cn_times = ["Proband", "Block", "Task", "Trial", "MappingMethod", "NumLayers", "Target", "Target_Relative", "Duration"]
# end_times = pd.DataFrame(columns = cn_times) 

timeFormat = "%Y-%m-%dT%H:%M:%S.%fZ"

probands = []

# iterate through all probands
for proband in cleanedStudy:

    start = proband[(proband['posX']  == " START")]
    # remove duplicate labels (keep last)
    start = start.drop_duplicates(['TaskNo', 'TrialIdx'], keep='last')
    
    finish = proband[(proband["posX"] == " COMPLETED") | (proband["posX"] == " FAILED") | (proband["posX"] == " TERMINATED")]
    
    # remove duplicate labels (keep first)
    finish = finish.drop_duplicates(['TaskNo', 'TrialIdx'])
    
    # setting the indices - associate the date sets with each other - nth start <-> nth finish 
    finish["FrameNumber_Start"] = start.index
    start["FrameNumber_Finish"] = finish.index
    
    start["DateTime"] = proband["DateTime"].astype("string")
    finish["DateTime"] = proband["DateTime"].astype("string")
    
    finish = finish.reset_index()
    start = start.reset_index()
    
    result = pd.DataFrame(start["mappingMethod"])
    result = result.rename(columns= {"mappingMethod": "MappingMethod"})
    
    result["FrameNumber_Start"] = finish["FrameNumber_Start"]
    result["FrameNumber_Finish"] = start["FrameNumber_Finish"]
    result["Block"] = (start["TaskNo"] / 18).apply(np.ceil).astype(int)
    result["Task"] = (start["TaskNo"] - ((result["Block"] - 1) * 18)).astype(int)
    result["Trial"] = start["TrialIdx"].astype(int)
    result["NumLayers"] = start["LayerCount"]    
    result["Target"] = start["TargetLayers"].str.split(",")
    result["Target"] = result.apply(lambda item: item["Target"][item["Trial"]], axis = 1).astype(int)
    result["Target_Relative"] = result["Target"].astype(float) / result["NumLayers"].astype(float)

    result["Duration"] = (pd.to_datetime(finish["DateTime"], format=timeFormat) - pd.to_datetime(start["DateTime"], format=timeFormat)).dt.total_seconds()
    result["Result"] = finish["posX"]
    
    result["Proband"] = start["Proband"]
    
    probands.append(result)

allTimes = pd.concat(probands, ignore_index=True)
display(allTimes)

allTimes.to_csv(rf'{export}times.csv', sep= ";")

,MappingMethod,FrameNumber_Start,FrameNumber_Finish,Block,Task,Trial,NumLayers,Target,Target_Relative,Duration,Result,Proband
0,direct,135,330,1,1,0,6,4,0.666667,12.221,COMPLETED,01
1,direct,413,531,1,1,1,6,5,0.833333,4.414,TERMINATED,01
2,direct,603,804,1,1,2,6,3,0.500000,7.155,COMPLETED,01
3,direct,870,969,1,1,3,6,1,0.166667,3.627,TERMINATED,01
4,direct,1029,1177,1,1,4,6,2,0.333333,5.516,COMPLETED,01
...,...,...,...,...,...,...,...,...,...,...,...,...
6205,widening,89346,89495,3,18,0,6,4,0.666667,7.359,COMPLETED,24
6206,widening,89542,89684,3,18,1,6,5,0.833333,5.325,COMPLETED,24
6207,widening,89739,89833,3,18,2,6,2,0.333333,3.438,TERMINATED,24
6208,widening,89887,90030,3,18,3,6,3,0.500000,5.467,COMPLETED,24
6209,widening,90074,90208,3,18,4,6,1,0.166667,5.088,FAILED,24

#### Versuchsdauer für jeden Trial und je Proband (Trial als eigene Spalten)

| PROBAND | BLOCK | TASK | TRIAL0 | ... | TRIALN | MAPPING_METHOD | NUM_LAYERS | TARGET | DURATION |
| ------- | ----- | ---- | ------ | --- | -------| -------------- | ---------- | ------ | ------   |
| 1       | 1     | 2    | 5.532s | ... | 2.546s | direct         | 15         | 7      | 15.532s  |
| .       | .     | .    | .      | ... | .      | .              | .          | .      | .        |
| .       | .     | .    | .      | ... | .      | .              | .          | .      | .        |

In [4]:
pivot = allTimes.pivot(index=["Proband", "Block", "Task", "MappingMethod", "NumLayers"], columns="Trial", values="Duration")

# print(end_times.columns)
# print(end_times.index)

# display(pivot.columns.names)
# print(pivot.index.names)

# creating the multiIndex... 
m_idx = pd.MultiIndex.from_frame(pivot)

# print(m_idx.get_level_values(0))
    
pivot["Duration_Sum"] = m_idx.get_level_values(0) +  m_idx.get_level_values(1) +  m_idx.get_level_values(2) +  m_idx.get_level_values(3) +  m_idx.get_level_values(4)

display(pivot)

pivot.to_csv(rf'{export}times_repeat.csv',sep= ";")

Trial                                            0       1       2       3  \
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6          12.221   4.414   7.155   3.627
              2     direct       9           9.300   6.029  13.550  11.628
              3     direct       9          11.357   7.849   6.402   4.394
              4     direct       15         10.526   7.910   7.202   7.145
              5     direct       12          9.006   8.612   8.256   5.049
...                                            ...     ...     ...     ...
24      3     14    widening     9           7.163   4.929   5.777   6.530
              15    widening     12         10.430   5.419   8.240   5.712
              16    widening     12         10.177  15.856   6.571   6.755
              17    widening     21         12.128   9.413   4.488   4.400
              18    widening     6           7.359   5.325   3.438   5.467

Trial                                           4  Duration_Sum
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6          5.516        32.933
              2     direct       9          9.832        50.339
              3     direct       9          8.062        38.064
              4     direct       15         7.956        40.739
              5     direct       12         4.624        35.547
...                                           ...           ...
24      3     14    widening     9          5.683        30.082
              15    widening     12         6.656        36.457
              16    widening     12         5.323        44.682
              17    widening     21         6.644        37.073
              18    widening     6          5.088        26.677

[1242 rows x 6 columns]

#### Ergebnis für jeden Trial und je Proband (Trial als eigene Spalten)

| PROBAND | BLOCK | TASK | TRIAL0    | ... | TRIALN | MAPPING_METHOD | NUM_LAYERS | TARGET | DURATION |
| ------- | ----- | ---- | --------- | --- | -------| -------------- | ---------- | ------ | ------   |
| 1       | 1     | 2    | COMPLETED | ... | FAILED | direct         | 15         | 7      | 15.532s  |
| .       | .     | .    | .         | ... | .      | .              | .          | .      | .        |
| .       | .     | .    | .         | ... | .      | .              | .          | .      | .        |

In [5]:
pivot = allResults.pivot(index=["Proband", "Block", "Task", "MappingMethod", "NumLayers"], columns="Trial", values=["Result", "Result_Numeric_Completed", "Result_Numeric_Failed", "Result_Numeric_Terminated"] )

# print(end_times.columns)
# print(end_times.index)

# display(pivot.columns.names)
# print(pivot.index.names)

# creating the multiIndex... 
m_idx = pd.MultiIndex.from_frame(pivot)

# print(m_idx.get_level_values(0))

pivot['rate_completed'] = (m_idx.get_level_values(5) +  m_idx.get_level_values(6) +  m_idx.get_level_values(7) +  m_idx.get_level_values(8) +  m_idx.get_level_values(9)) / 5
pivot['rate_failed'] = (m_idx.get_level_values(10) +  m_idx.get_level_values(11) +  m_idx.get_level_values(12) +  m_idx.get_level_values(13) +  m_idx.get_level_values(14)) / 5
pivot['rate_terminated'] = (m_idx.get_level_values(15) +  m_idx.get_level_values(16) +  m_idx.get_level_values(17) +  m_idx.get_level_values(18) +  m_idx.get_level_values(19)) / 5

pivot['rate_sum'] = pivot['rate_completed'] + pivot['rate_failed'] + pivot['rate_terminated']

display(pivot)

pivot.to_csv(rf'{export}results_repeat.csv',sep= ";")

                                                Result               \
Trial                                                0            1
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6           COMPLETED   TERMINATED
              2     direct       9           COMPLETED    COMPLETED
              3     direct       9           COMPLETED    COMPLETED
              4     direct       15          COMPLETED    COMPLETED
              5     direct       12          COMPLETED    COMPLETED
...                                                ...          ...
24      3     14    widening     9              FAILED   TERMINATED
              15    widening     12          COMPLETED   TERMINATED
              16    widening     12          COMPLETED    COMPLETED
              17    widening     21          COMPLETED    COMPLETED
              18    widening     6           COMPLETED    COMPLETED

                                                                      \
Trial                                                 2            3
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6            COMPLETED   TERMINATED
              2     direct       9           TERMINATED    COMPLETED
              3     direct       9            COMPLETED   TERMINATED
              4     direct       15          TERMINATED   TERMINATED
              5     direct       12           COMPLETED   TERMINATED
...                                                 ...          ...
24      3     14    widening     9            COMPLETED    COMPLETED
              15    widening     12           COMPLETED       FAILED
              16    widening     12           COMPLETED    COMPLETED
              17    widening     21          TERMINATED   TERMINATED
              18    widening     6           TERMINATED    COMPLETED

                                                         \
Trial                                                 4
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6            COMPLETED
              2     direct       9           TERMINATED
              3     direct       9            COMPLETED
              4     direct       15          TERMINATED
              5     direct       12          TERMINATED
...                                                 ...
24      3     14    widening     9            COMPLETED
              15    widening     12           COMPLETED
              16    widening     12          TERMINATED
              17    widening     21              FAILED
              18    widening     6               FAILED

                                           Result_Numeric_Completed           \
Trial                                                             0  1  2  3
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6                                1  0  1  0
              2     direct       9                                1  1  0  1
              3     direct       9                                1  1  1  0
              4     direct       15                               1  1  0  0
              5     direct       12                               1  1  1  0
...                                                             ... .. .. ..
24      3     14    widening     9                                0  0  1  1
              15    widening     12                               1  0  1  0
              16    widening     12                               1  1  1  1
              17    widening     21                               1  1  0  0
              18    widening     6                                1  1  0  1

                                               ... Result_Numeric_Failed  \
Trial                                       4  ...                     4
Proband Block Task MappingMethod NumLayers     ...
01      1     1     direct       6          1  ...                     0
              2     direct       9          0  ...                     0
              3     direct       9          1  ...                     0
              4     direct       15         0  ...                     0
              5     direct       12         0  ...                     0
...                                        ..  ...                   ...
24      3     14    widening     9          1  ...                     0
              15    widening     12         1  ...                     0
              16    widening     12         0  ...                     0
              17    widening     21         0  ...                     1
              18    widening     6          0  ...                     1

                                           Result_Numeric_Terminated           \
Trial                                                              0  1  2  3
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6                                 0  1  0  1
              2     direct       9                                 0  0  1  0
              3     direct       9                                 0  0  0  1
              4     direct       15                                0  0  1  1
              5     direct       12                                0  0  0  1
...                                                              ... .. .. ..
24      3     14    widening     9                                 0  1  0  0
              15    widening     12                                0  1  0  0
              16    widening     12                                0  0  0  0
              17    widening     21                                0  0  1  1
              18    widening     6                                 0  0  1  0

                                              rate_completed rate_failed  \
Trial                                       4
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6          0            0.6         0.0
              2     direct       9          1            0.6         0.0
              3     direct       9          0            0.8         0.0
              4     direct       15         1            0.4         0.0
              5     direct       12         1            0.6         0.0
...                                        ..            ...         ...
24      3     14    widening     9          0            0.6         0.2
              15    widening     12         0            0.6         0.2
              16    widening     12         1            0.8         0.0
              17    widening     21         0            0.4         0.2
              18    widening     6          0            0.6         0.2

                                           rate_terminated rate_sum
Trial
Proband Block Task MappingMethod NumLayers
01      1     1     direct       6                     0.4      1.0
              2     direct       9                     0.4      1.0
              3     direct       9                     0.2      1.0
              4     direct       15                    0.6      1.0
              5     direct       12                    0.4      1.0
...                                                    ...      ...
24      3     14    widening     9                     0.2      1.0
              15    widening     12                    0.2      1.0
              16    widening     12                    0.2      1.0
              17    widening     21                    0.4      1.0
              18    widening     6                     0.2      1.0

[1242 rows x 24 columns]

---
#### Erfolg/Fehlerquote über alle Probanden je Ebenenanzahl

| NUM_LAYERS     | COMPLETED | FAILED  | TERMINATED | SUM |
| ---            | ---       | ---     | ---        | --- |
| 5              | 2 / 20%   | 5 / 50% | 3 / 30%    | 10  |
| .              | .         | .       | .          | .   |
| .              | .         | .       | .          | .   |
---

In [35]:
df_resultStat = pd.read_csv(rf'{export}results.csv', sep=";")
# df_resultStat = df_resultStat.iloc[1: , :]

cn_rates = ["NumLayers", "Completed_Abs", "Completed_Rel", "Failed_Abs", "Failed_Rel", "Terminated_Abs", "Terminated_Rel", "Sum"]
df_rates = pd.DataFrame(columns = cn_rates) 

# select all combinations of mappng method / num layers
# allConditions = df_resultStat.drop_duplicates(subset=["MappingMethod", "NumLayers"])[["MappingMethod", "NumLayers"]]

grouped = df_resultStat.groupby(["NumLayers", "Result"]) 

groups = df_resultStat.groupby(["NumLayers"])

for elem in groups:
    df_rates.loc[len(df_rates)] = [elem[0], 0, 0, 0, 0, 0, 0, 0]

count = grouped["Result"].count()

for index, value in count.items():
    rate = df_rates.loc[(df_rates["NumLayers"] == index[0])]
    r_index = rate.index
        
    if index[1] == " COMPLETED":
        compl_sum = int(rate["Completed_Abs"]) + value;
        df_rates.iat[r_index[0], 1] = compl_sum
        
    if index[1] == " FAILED":
        fail_sum = int(rate["Failed_Abs"]) + value;
        df_rates.iat[r_index[0], 3] = fail_sum
        
    if index[1] == " TERMINATED":
        term_sum = int(rate["Terminated_Abs"]) + value;
        df_rates.iat[r_index[0], 5] = term_sum
    
df_rates["Sum"] = df_rates["Completed_Abs"] + df_rates["Failed_Abs"] + df_rates["Terminated_Abs"]
df_rates["Completed_Rel"] = df_rates["Completed_Abs"] / df_rates["Sum"]
df_rates["Failed_Rel"] = df_rates["Failed_Abs"] / df_rates["Sum"]
df_rates["Terminated_Rel"] = df_rates["Terminated_Abs"] / df_rates["Sum"]

df_rates["Sum_Rel"] = df_rates["Completed_Rel"] + df_rates["Failed_Rel"] + df_rates["Terminated_Rel"]
    
display(df_rates.sort_values(by="NumLayers", key=lambda col: col.astype(int)))

df_rates.to_csv(rf'{export}rates_global_layers.csv', sep= ";")

,NumLayers,Completed_Abs,Completed_Rel,Failed_Abs,Failed_Rel,Terminated_Abs,Terminated_Rel,Sum,Sum_Rel
0,6,741,0.715942,13,0.0125604,281,0.271498,1035,1
1,9,771,0.744928,16,0.0154589,248,0.239614,1035,1
2,12,732,0.707246,15,0.0144928,288,0.278261,1035,1
3,15,721,0.696618,27,0.026087,287,0.277295,1035,1
4,18,708,0.684058,27,0.026087,300,0.289855,1035,1
5,21,676,0.65314,37,0.0357488,322,0.311111,1035,1

#### Dauer über alle Probanden je Ebenenanzahl

| NUM_LAYERS     | COMPLETED | FAILED  | TERMINATED | SUM |
| ---            | ---       | ---     | ---        | --- |
| 5              | 2 / 40s   | 5 / 80s | 3 / 60s    | 10  |
| .              | .         | .       | .          | .   |
| .              | .         | .       | .          | .   |
---

In [49]:
df_resultStat = pd.read_csv(rf'{export}times.csv', sep=";")
# df_resultStat = df_resultStat.iloc[1: , :]

cn_times = ["NumLayers", "Sum_Num", "Sum_Total", "All_Avg"]
df_times = pd.DataFrame() 

# select all combinations of mappng method / num layers

# group all byNumLayers and Result
# compute sum and count for each combination
# pivot results into columns
grouped = df_resultStat.groupby(["NumLayers", "Result"])["Duration"].agg(["sum", "count", "mean"]).reset_index().pivot(index="NumLayers", columns="Result")
m_idx = pd.MultiIndex.from_frame(grouped)

# display(grouped)

# now only for formatting and additional sums: extract multi index values 
df_times["NumLayers"] = grouped.index

df_times["Completed_Num"] = m_idx.get_level_values(3)
df_times["Completed_Total"] = m_idx.get_level_values(0)
df_times["Completed_Avg"] = m_idx.get_level_values(6)

df_times["Failed_Num"] = m_idx.get_level_values(4)
df_times["Failed_Total"] = m_idx.get_level_values(1)
df_times["Failed_Avg"] = m_idx.get_level_values(7)

df_times["Terminated_Num"] = m_idx.get_level_values(5)
df_times["Terminated_Total"] = m_idx.get_level_values(2)
df_times["Terminated_Avg"] = m_idx.get_level_values(8)

df_times["Sum_Num"] = df_times["Completed_Num"] + df_times["Failed_Num"] + df_times["Terminated_Num"]
df_times["Sum_Total"] = df_times["Completed_Total"] + df_times["Failed_Total"] + df_times["Terminated_Total"]
df_times["All_Avg"] = df_times["Sum_Total"] / df_times["Sum_Num"]


display(df_times)

df_times.to_csv(rf'{export}times_global_layers.csv', sep= ";")

,NumLayers,Completed_Num,Completed_Total,Completed_Avg,Failed_Num,Failed_Total,Failed_Avg,Terminated_Num,Terminated_Total,Terminated_Avg,Sum_Num,Sum_Total,All_Avg
0,6,741,7459.320,10.066559,13,156.503,12.038692,281,1482.331,5.275199,1035,9098.154,8.790487
1,9,771,9619.059,12.476082,16,134.370,8.398125,248,1967.014,7.931508,1035,11720.443,11.324100
2,12,732,8455.875,11.551742,15,110.883,7.392200,288,2048.191,7.111774,1035,10614.949,10.255989
3,15,721,7908.313,10.968534,27,374.777,13.880630,287,3508.049,12.223167,1035,11791.139,11.392405
4,18,708,9478.806,13.388144,27,431.385,15.977222,300,3524.329,11.747763,1035,13434.520,12.980213
5,21,676,9325.736,13.795467,37,455.933,12.322514,322,2919.135,9.065637,1035,12700.804,12.271308

---
#### Erfolg/Fehlerquote über je Probanden je Ebenenanzahl

| Proband     | NUM_LAYERS     | COMPLETED | FAILED  | TERMINATED | SUM |
| ---         | ---            | ---       | ---     | ---        | --- |
| 0           | 5              | 2 / 20%   | 5 / 50% | 3 / 30%    | 10  |
| .           | .              | .         | .       | .          | .   |
| .           | .              | .         | .       | .          | .   |
---

In [50]:
df_resultStat = pd.read_csv(rf'{export}results.csv', sep=";")
# df_resultStat = df_resultStat.iloc[1: , :]

cn_rates = ["Proband", "NumLayers", "Completed_Abs", "Completed_Rel", "Failed_Abs", "Failed_Rel", "Terminated_Abs", "Terminated_Rel", "Sum"]
df_rates = pd.DataFrame(columns = cn_rates) 

# select all combinations of mappng method / num layers
# allConditions = df_resultStat.drop_duplicates(subset=["MappingMethod", "NumLayers"])[["MappingMethod", "NumLayers"]]

grouped = df_resultStat.groupby(["Proband", "NumLayers", "Result"]) 

groups = df_resultStat.groupby(["Proband", "NumLayers"])

for elem in groups:
    df_rates.loc[len(df_rates)] = [elem[0][0], elem[0][1], 0, 0, 0, 0, 0, 0, 0]

    
count = grouped["Result"].count()

for index, value in count.items():
    rate = df_rates.loc[(df_rates["Proband"] == index[0]) & (df_rates["NumLayers"] == index[1])]
    r_index = rate.index
        
    if index[2] == " COMPLETED":
        compl_sum = int(rate["Completed_Abs"]) + value;
        df_rates.iat[r_index[0], 2] = compl_sum
        
    if index[2] == " FAILED":
        fail_sum = int(rate["Failed_Abs"]) + value;
        df_rates.iat[r_index[0], 4] = fail_sum
        
    if index[2] == " TERMINATED":
        term_sum = int(rate["Terminated_Abs"]) + value;
        df_rates.iat[r_index[0], 6] = term_sum
    
df_rates["Sum"] = df_rates["Completed_Abs"] + df_rates["Failed_Abs"] + df_rates["Terminated_Abs"]
df_rates["Completed_Rel"] = df_rates["Completed_Abs"] / df_rates["Sum"]
df_rates["Failed_Rel"] = df_rates["Failed_Abs"] / df_rates["Sum"]
df_rates["Terminated_Rel"] = df_rates["Terminated_Abs"] / df_rates["Sum"]

df_rates["Sum_Rel"] = df_rates["Completed_Rel"] + df_rates["Failed_Rel"] + df_rates["Terminated_Rel"]
    
display(df_rates.sort_values(by=["Proband", "NumLayers"], key=lambda col: col.astype(int)))

df_rates.to_csv(rf'{export}rates_subject_layers.csv', sep= ";")

,Proband,NumLayers,Completed_Abs,Completed_Rel,Failed_Abs,Failed_Rel,Terminated_Abs,Terminated_Rel,Sum,Sum_Rel
0,1,6,27,0.6,0,0,18,0.4,45,1
1,1,9,31,0.688889,0,0,14,0.311111,45,1
2,1,12,29,0.644444,1,0.0222222,15,0.333333,45,1
3,1,15,33,0.733333,2,0.0444444,10,0.222222,45,1
4,1,18,31,0.688889,1,0.0222222,13,0.288889,45,1
...,...,...,...,...,...,...,...,...,...,...
133,24,9,31,0.688889,4,0.0888889,10,0.222222,45,1
134,24,12,30,0.666667,2,0.0444444,13,0.288889,45,1
135,24,15,27,0.6,4,0.0888889,14,0.311111,45,1
136,24,18,27,0.6,7,0.155556,11,0.244444,45,1
137,24,21,30,0.666667,5,0.111111,10,0.222222,45,1

---
#### Erfolg/Fehlerquote über alle Probanden je Ebenenanzahl und mapping methode

| MAPPING_METHOD | NUM_LAYERS | COMPLETED | FAILED  | TERMINATED | SUM |
| ---            | ---        | ---       | ---     | ---        | --- |
| direct         | 5          | 2 / 20%   | 5 / 50% | 3 / 30%    | 10  |
| .              | .          | .         | .       | .          | .   |
| .              | .          | .         | .       | .          | .   |
---

In [8]:
df_resultStat = pd.read_csv(rf'{export}results.csv', sep=";")
#df_resultStat = df_resultStat.iloc[0: , :]

cn_rates = ["MappingMethod", "NumLayers", "Completed_Abs", "Completed_Rel", "Failed_Abs", "Failed_Rel", "Terminated_Abs", "Terminated_Rel", "Sum"]
df_rates = pd.DataFrame(columns = cn_rates) 

# select all combinations of mappng method / num layers
# allConditions = df_resultStat.drop_duplicates(subset=["MappingMethod", "NumLayers"])[["MappingMethod", "NumLayers"]]

grouped = df_resultStat.groupby(["MappingMethod", "NumLayers", "Result"]) 

groups = df_resultStat.groupby(["MappingMethod", "NumLayers"])

for elem in groups:
    df_rates.loc[len(df_rates)] = [elem[0][0], elem[0][1], 0, 0, 0, 0, 0, 0, 0]
    
count = grouped["Result"].count()

for index, value in count.items():
    rate = df_rates.loc[(df_rates["MappingMethod"] == index[0]) & (df_rates["NumLayers"] == index[1])]
    r_index = rate.index
        
    if index[2] == " COMPLETED":
        compl_sum = int(rate["Completed_Abs"]) + value;
        df_rates.iat[r_index[0], 2] = compl_sum
        
    elif index[2] == " FAILED":
        fail_sum = int(rate["Failed_Abs"]) + value;
        df_rates.iat[r_index[0], 4] = fail_sum
        
    elif index[2] == " TERMINATED":
        term_sum = int(rate["Terminated_Abs"]) + value;
        df_rates.iat[r_index[0], 6] = term_sum
        
    else:
        print(index[2])
    
df_rates["Sum"] = df_rates["Completed_Abs"] + df_rates["Failed_Abs"] + df_rates["Terminated_Abs"]
df_rates["Completed_Rel"] = df_rates["Completed_Abs"] / df_rates["Sum"]
df_rates["Failed_Rel"] = df_rates["Failed_Abs"] / df_rates["Sum"]
df_rates["Terminated_Rel"] = df_rates["Terminated_Abs"] / df_rates["Sum"]

df_rates["Sum_Rel"] = df_rates["Completed_Rel"] + df_rates["Failed_Rel"] + df_rates["Terminated_Rel"]
    
display(df_rates.sort_values(by=["MappingMethod", "NumLayers"]))

df_rates.to_csv(rf'{export}rates_global_mapping_layers.csv', sep= ";")

,MappingMethod,NumLayers,Completed_Abs,Completed_Rel,Failed_Abs,Failed_Rel,Terminated_Abs,Terminated_Rel,Sum,Sum_Rel
0,densening,6,254,0.736232,3,0.00869565,88,0.255072,345,1
1,densening,9,276,0.8,6,0.0173913,63,0.182609,345,1
2,densening,12,261,0.756522,1,0.00289855,83,0.24058,345,1
3,densening,15,262,0.75942,3,0.00869565,80,0.231884,345,1
4,densening,18,263,0.762319,4,0.0115942,78,0.226087,345,1
5,densening,21,239,0.692754,5,0.0144928,101,0.292754,345,1
6,direct,6,255,0.73913,2,0.0057971,88,0.255072,345,1
7,direct,9,275,0.797101,3,0.00869565,67,0.194203,345,1
8,direct,12,255,0.73913,4,0.0115942,86,0.249275,345,1
9,direct,15,254,0.736232,8,0.0231884,83,0.24058,345,1
10,direct,18,242,0.701449,7,0.0202899,96,0.278261,345,1
11,direct,21,241,0.698551,7,0.0202899,97,0.281159,345,1
12,widening,6,232,0.672464,8,0.0231884,105,0.304348,345,1
13,widening,9,220,0.637681,7,0.0202899,118,0.342029,345,1
14,widening,12,216,0.626087,10,0.0289855,119,0.344928,345,1
15,widening,15,205,0.594203,16,0.0463768,124,0.35942,345,1
16,widening,18,203,0.588406,16,0.0463768,126,0.365217,345,1
17,widening,21,196,0.568116,25,0.0724638,124,0.35942,345,1

---
#### Erfolg/Fehlerquote über je Proband je Ebenenanzahl und mapping methode

| Proband | MAPPING_METHOD | NUM_LAYERS | COMPLETED | FAILED  | TERMINATED | SUM |
| ---     | ---            | ---        | ---       | ---     | ---        | --- |
| 0       | direct         | 5          | 2 / 20%   | 5 / 50% | 3 / 30%    | 10  |
| .       | .              | .          | .         | .       | .          | .   |
| .       | .              | .          | .         | .       | .          | .   |
---

In [9]:
df_resultStat = pd.read_csv(rf'{export}results.csv', sep=";")
# df_resultStat = df_resultStat.iloc[1: , :]

cn_rates = ["Proband", "MappingMethod", "NumLayers", "Completed_Abs", "Completed_Rel", "Failed_Abs", "Failed_Rel", "Terminated_Abs", "Terminated_Rel", "Sum"]
df_rates = pd.DataFrame(columns = cn_rates) 

# select all combinations of mappng method / num layers
# allConditions = df_resultStat.drop_duplicates(subset=["MappingMethod", "NumLayers"])[["MappingMethod", "NumLayers"]]

grouped = df_resultStat.groupby(["Proband", "MappingMethod", "NumLayers", "Result"]) 

groups = df_resultStat.groupby(["Proband", "MappingMethod", "NumLayers"])

for elem in groups:
    df_rates.loc[len(df_rates)] = [elem[0][0], elem[0][1], elem[0][2], 0, 0, 0, 0, 0, 0, 0]

count = grouped["Result"].count()

for index, value in count.items():
    rate = df_rates.loc[(df_rates["Proband"] == index[0]) & (df_rates["MappingMethod"] == index[1]) & (df_rates["NumLayers"] == index[2])]
    r_index = rate.index
        
    if index[3] == " COMPLETED":
        compl_sum = int(rate["Completed_Abs"]) + value;
        df_rates.iat[r_index[0], 3] = compl_sum
        
    if index[3] == " FAILED":
        fail_sum = int(rate["Failed_Abs"]) + value;
        df_rates.iat[r_index[0], 5] = fail_sum
        
    if index[3] == " TERMINATED":
        term_sum = int(rate["Terminated_Abs"]) + value;
        df_rates.iat[r_index[0], 7] = term_sum
        
    
df_rates["Sum"] = df_rates["Completed_Abs"] + df_rates["Failed_Abs"] + df_rates["Terminated_Abs"]
df_rates["Completed_Rel"] = df_rates["Completed_Abs"] / df_rates["Sum"]
df_rates["Failed_Rel"] = df_rates["Failed_Abs"] / df_rates["Sum"]
df_rates["Terminated_Rel"] = df_rates["Terminated_Abs"] / df_rates["Sum"]

df_rates["Sum_Rel"] = df_rates["Completed_Rel"] + df_rates["Failed_Rel"] + df_rates["Terminated_Rel"]
    
display(df_rates.sort_values(by=["Proband", "MappingMethod", "NumLayers"]))

df_rates.to_csv(rf'{export}rates_subject_mapping_layers.csv', sep= ";")

,Proband,MappingMethod,NumLayers,Completed_Abs,Completed_Rel,Failed_Abs,Failed_Rel,Terminated_Abs,Terminated_Rel,Sum,Sum_Rel
0,1,densening,6,9,0.6,0,0,6,0.4,15,1
1,1,densening,9,11,0.733333,0,0,4,0.266667,15,1
2,1,densening,12,10,0.666667,0,0,5,0.333333,15,1
3,1,densening,15,14,0.933333,0,0,1,0.0666667,15,1
4,1,densening,18,10,0.666667,0,0,5,0.333333,15,1
...,...,...,...,...,...,...,...,...,...,...,...
409,24,widening,9,8,0.533333,2,0.133333,5,0.333333,15,1
410,24,widening,12,10,0.666667,1,0.0666667,4,0.266667,15,1
411,24,widening,15,8,0.533333,0,0,7,0.466667,15,1
412,24,widening,18,7,0.466667,4,0.266667,4,0.266667,15,1
413,24,widening,21,8,0.533333,3,0.2,4,0.266667,15,1

---
#### Versuchsdauer über alle Probanden (nach Outcome)
| MAPPING_METHOD | NUM_LAYERS | COMPLETED | FAILED | TERMINATED | AVG     |
| ---            | ---        | ---       | ---    | ---        | ---     |
| direct         | 5          | 10.145s   | 9.759s | 11.763s    | 10.345s |
| .              | .          | .         | .       | .          | .      |
| .              | .          | .         | .       | .          | .      |
---

---
#### Versuchsdauer je Proband je Ebenenanzahl und mapping methode

| Proband | MAPPING_METHOD | NUM_LAYERS | COMPLETED | FAILED  | TERMINATED | SUM |
| ---     | ---            | ---        | ---       | ---     | ---        | --- |
| 0       | direct         | 5          | 2 / 20%   | 5 / 50% | 3 / 30%    | 10  |
| .       | .              | .          | .         | .       | .          | .   |
| .       | .              | .          | .         | .       | .          | .   |
---

In [62]:
df_resultStat = pd.read_csv(rf'{export}times.csv', sep=";")
# df_resultStat = df_resultStat.iloc[1: , :]

cn_times = ["Proband", "MappingMethod", "NumLayers", "Completed_Sum", "Completed_Avg", "Completed_Num", "Failed_Sum", "Failed_Avg", "Failed_Num", "Terminated_Sum", "Terminated_Avg", "Terminated_Num", "All_Sum", "All_Avg", "All_Num"]
df_times = pd.DataFrame(columns = cn_times) 

# select all combinations of mappng method / num layers
# allConditions = df_resultStat.drop_duplicates(subset=["MappingMethod", "NumLayers"])[["MappingMethod", "NumLayers"]]

grouped = df_resultStat.groupby(["Proband", "MappingMethod", "NumLayers", "Result"]) 

groups = df_resultStat.groupby(["Proband", "MappingMethod", "NumLayers"])

# stats = df_resultStat.groupby(["Proband", "MappingMethod", "NumLayers", "Duration"])["Duration"].mean()

# print(stats)

# convert solumns to floats to prevent division by zero error
df_times["Completed_Sum"] = df_times["Completed_Sum"].astype('float64')
df_times["Completed_Num"] = df_times["Completed_Num"].astype('float64')
df_times["Failed_Sum"] = df_times["Failed_Sum"].astype('float64')
df_times["Failed_Num"] = df_times["Failed_Num"].astype('float64')
df_times["Terminated_Sum"] = df_times["Terminated_Sum"].astype('float64')
df_times["Terminated_Num"] = df_times["Terminated_Num"].astype('float64')
df_times["All_Sum"] = df_times["All_Sum"].astype('float64')
df_times["All_Num"] = df_times["All_Num"].astype('float64')

for elem in groups:
    df_times.loc[len(df_times)] = [elem[0][0], elem[0][1], elem[0][2], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

count = grouped["Duration"].sum()

for index, value in count.items():
    display(value)
    
    time = df_times.loc[(df_times["Proband"] == index[0]) & (df_times["MappingMethod"] == index[1]) & (df_times["NumLayers"] == index[2])]
    t_index = time.index
        
    if index[3] == " COMPLETED":
        compl_sum = time["Completed_Sum"] + value;
        df_times.iat[t_index[0], 3] = compl_sum
        df_times.iat[t_index[0], 5] += 1
        
    if index[3] == " FAILED":
        fail_sum = time["Failed_Sum"] + value;
        df_times.iat[t_index[0], 6] = fail_sum
        df_times.iat[t_index[0], 8] += 1
        
    if index[3] == " TERMINATED":
        term_sum = time["Terminated_Sum"] + value;
        df_times.iat[t_index[0], 9] = term_sum
        df_times.iat[t_index[0], 11] += 1
        
df_times["All_Sum"] = df_times["Completed_Sum"] + df_times["Failed_Sum"] + df_times["Terminated_Sum"]
df_times["All_Num"] = df_times["Completed_Num"] + df_times["Failed_Num"] + df_times["Terminated_Num"]
df_times["Completed_Avg"] = (df_times["Completed_Sum"] / df_times["Completed_Num"]).replace(np.inf, 0).replace(np.nan, 0)
df_times["Failed_Avg"] = (df_times["Failed_Sum"] / df_times["Failed_Num"]).replace(np.inf, 0).replace(np.nan, 0)
df_times["Terminated_Avg"] = (df_times["Terminated_Sum"] / df_times["Terminated_Num"]).replace(np.inf, 0).replace(np.nan, 0)

df_times["All_Avg"] = (df_times["All_Sum"] / df_times["All_Num"]).replace(np.inf, 0).replace(np.nan, 0)
    
display(df_times.sort_values(by=["Proband", "MappingMethod", "NumLayers"]))

df_times.to_csv(rf'{export}times_subject_mapping_layers.csv', sep= ";")

65.216

25.868

75.472

16.724

298.49800000000005

31.782000000000004

112.09

6.838

88.58600000000001

34.726000000000006

85.357

40.676

70.66799999999999

23.05

98.234

27.776000000000003

91.84

26.481

73.80599999999998

10.104

38.634

77.30900000000001

9.593

28.318

93.245

8.982000000000001

84.01400000000001

122.90700000000001

29.701

52.295

66.45400000000001

62.647000000000006

8.897

32.660000000000004

91.863

15.782000000000002

25.232000000000003

96.472

49.422

60.256

21.96

44.16

93.796

3.73

332.74800000000005

129.39499999999998

170.945

22.132

178.285

17.778000000000002

176.517

22.195

85.82700000000001

12.382000000000001

128.744

15.519000000000002

163.986

7.271000000000001

119.10399999999998

20.177

123.319

114.471

122.195

8.875

41.822

853.5960000000001

13.352000000000002

107.459

9.525

139.499

7.706

27.880000000000003

74.037

8.288

74.396

149.75500000000002

35.269000000000005

7.666

137.66400000000002

17.685000000000002

33.995999999999995

59.652

5.376

20.272000000000002

88.73299999999999

21.418

74.21600000000001

39.286

131.5

34.093

129.538

88.171

94.083

108.287

32.596000000000004

3.753

79.428

42.985

6.181

56.64

47.041

81.108

68.798

76.128

68.416

26.796000000000003

148.36100000000002

61.665000000000006

150.626

253.61400000000003

28.162

63.524

4.432

37.413000000000004

102.74799999999999

26.881999999999998

53.032

16.323000000000004

26.046000000000006

-11.248000000000001

174.031

34.398

57.464999999999996

90.293

62.307

33.541000000000004

113.84400000000001

22.802000000000003

103.76400000000001

35.994

113.96600000000001

143.39200000000002

54.876

256.37100000000004

102.79

160.896

64.202

33.058

66.676

46.141000000000005

49.428

105.739

59.206999999999994

129.942

402.59200000000004

177.362

79.611

208.70000000000005

73.87500000000001

31.705000000000005

81.961

83.108

43.544

136.869

35.753

203.23299999999998

167.151

169.37399999999997

53.413000000000004

244.077

80.04500000000002

21.072000000000003

91.715

7.2090000000000005

126.88400000000001

113.056

33.84

132.446

9.802

118.26000000000002

23.004

69.16900000000001

11.818

85.225

16.355

105.21100000000001

12.197000000000001

81.95200000000001

42.896

90.716

52.186

93.14100000000002

47.733999999999995

79.32600000000001

8.955

66.54

28.668999999999997

95.61900000000001

21.731

89.026

6.21

36.036

93.878

44.799

92.994

45.121

104.93200000000002

19.476

126.63700000000001

33.604

130.628

22.578

210.91899999999998

86.657

50.009

104.054

56.656

99.08900000000001

8.853000000000002

85.52199999999999

34.56

109.85600000000001

27.076

105.75200000000002

33.518

355.90600000000006

67.535

142.215

48.959

115.03200000000002

4.989

382.0200000000001

44.953

85.309

59.970000000000006

102.65000000000002

19.556

13.3

129.526

9.433

36.198

102.029

56.054

46.012

248.042

109.89000000000001

3.415

122.15500000000002

83.23400000000001

67.189

127.585

12.794

81.238

69.28

70.739

51.544000000000004

1043.8750000000002

10.785

110.45100000000001

27.718000000000004

120.06900000000002

25.553

117.48700000000001

31.161

130.67900000000003

47.486000000000004

66.28800000000001

32.138

108.09700000000001

39.564

179.912

17.27

111.676

11.183

42.943

123.404

10.153

18.029

154.585

32.753

28.085

104.89599999999999

47.689

236.41000000000003

13.888000000000002

31.214

91.391

127.99100000000001

161.47000000000003

29.608000000000004

182.527

41.107

113.81800000000001

107.602

65.449

41.513999999999996

167.401

9.113

106.58800000000001

16.208

207.81500000000003

17.429000000000002

100.44999999999999

92.09700000000001

456.493

48.647

182.416

16.548000000000002

314.971

57.074000000000005

126.05699999999999

48.20399999999999

145.066

38.904

36.022000000000006

139.986

205.11599999999999

95.14399999999999

125.88100000000001

7.549

115.75800000000001

315.4630000000001

122.721

11.438

159.09100000000004

42.036

4.851

147.535

37.959

132.666

31.849000000000004

248.88400000000004

5.305000000000001

98.788

5.926

133.8

164.93300000000002

13.456

143.441

7.83

122.30500000000002

17.065

96.48600000000002

18.046

81.828

41.235

119.82700000000001

36.45099999999999

143.38199999999998

50.74

108.45000000000002

106.34800000000001

84.009

110.03

30.310000000000002

5.158

46.326000000000015

34.636

27.978

42.069

31.688000000000002

7.504

86.34599999999999

88.40200000000002

55.246

117.67000000000002

7.260000000000001

58.443

94.99

61.86300000000001

62.65800000000001

27.396

55.578

319.06799999999987

6.083

33.32

21.327

6.173

65.29899999999999

12.402000000000001

8.912

85.17200000000001

93.422

35.491

48.91400000000001

63.38

124.66000000000001

36.790000000000006

31.64

38.175000000000004

36.07000000000001

64.26100000000001

46.08200000000001

29.002000000000002

53.406000000000006

38.417

13.498000000000001

55.289

51.506

42.117999999999995

65.872

183.40400000000002

7.998

60.068

85.07400000000001

27.479

-7.053000000000001

96.43900000000002

89.815

25.976999999999997

91.99799999999999

40.05200000000001

388.167

-12.008

48.321

104.978

31.504999999999995

203.958

96.392

0.3370000000000002

128.62099999999998

-9.891

97.133

49.186

31.464999999999996

116.132

99.308

46.057

54.106000000000016

53.568

37.122

52.971000000000004

57.009

73.02100000000002

50.006

75.597

122.82300000000001

38.258

68.824

12.489

91.166

85.75900000000001

13.129999999999999

100.116

5.4350000000000005

112.48700000000002

17.834

108.09899999999999

14.290000000000001

128.871

476.99500000000006

15.932

96.70100000000001

6.219

125.946

94.88700000000001

21.842000000000002

135.913

33.004000000000005

113.37300000000002

24.779000000000003

155.46599999999998

84.268

4.152

76.618

308.30300000000005

90.90500000000002

29.602000000000004

77.08500000000001

44.24100000000001

106.28499999999998

27.201

79.196

55.336999999999996

90.605

23.337000000000003

124.393

7.9190000000000005

212.547

117.287

401.216

42.57600000000001

124.20800000000001

58.794000000000004

189.895

17.176000000000002

374.28400000000005

43.455

125.77300000000001

137.89600000000002

10.409

135.10399999999998

59.67

19.752

120.26400000000001

43.246

116.94200000000001

8.486

46.315

103.25999999999999

19.62

123.24199999999999

24.064

109.416

42.496

97.767

162.466

101.54099999999998

216.365

188.316

24.606

59.016999999999996

109.03800000000001

-3.564

353.314

8.902000000000001

427.53800000000007

-7.3149999999999995

452.036

-21.049999999999997

151.424

11.867

293.122

9.002

-579.889

-10.356

-501.41499999999996

-60.466

261.27499999999986

-184.14600000000002

-24.7170000000001

561.019

83.835

-66.111

46.25900000000017

-572.3570000000001

769.7420000000001

-228.685

669.532

-285.297

753.783

-539.81

-18.916000000000054

140.573

474.869

133.21200000000005

723.8990000000002

-541.0210000000001

69.333

44.126

497.722

7.973000000000001

162.737

21.566

137.993

13.269000000000002

155.81300000000002

12.446000000000002

202.093

14.211

64.569

150.804

113.61899999999999

23.037000000000006

134.21400000000003

162.43500000000003

20.222

145.65

254.45700000000002

99.414

14.094000000000001

125.167

18.911

5.73

96.48599999999999

38.403999999999996

158.548

41.599999999999994

137.057

9.001000000000001

24.031

142.82999999999998

35.221999999999994

8.266

55.733000000000004

43.006

-4.086

29.264

216.53699999999998

39.74100000000001

97.202

91.142

-1.066

54.118

124.262

44.82000000000001

105.041

41.429

72.09700000000001

33.982

86.06300000000002

33.25000000000001

82.673

85.703

345.893

50.197

58.205

128.269

-11.332

237.691

35.056

42.628

26.135

48.022

68.88900000000001

124.21600000000001

59.53000000000001

63.128000000000014

64.447

82.31

80.376

-2.563

111.367

122.569

-5.609

175.34799999999998

98.07900000000001

4.873

120.944

8.676

74.851

508.766

114.46

14.488000000000001

108.19500000000001

5.847

5.415

79.273

6.420000000000001

43.154

82.67899999999999

7.4079999999999995

92.80499999999999

5.898000000000001

79.827

6.674

25.464

122.239

11.790000000000001

257.972

32.42

85.50200000000002

15.038

19.631

105.74

8.908000000000001

22.373

91.56

31.344

18.546

58.321999999999996

24.079

32.788

56.672000000000004

16.23

71.70400000000001

53.135999999999996

6.751

47.080000000000005

102.679

95.26500000000001

5.382000000000001

373.948

17.91

101.113

4.814

180.599

7.399

121.429

13.788

182.42200000000003

16.241

87.903

64.156

96.211

103.175

108.25800000000001

22.332

114.303

105.90800000000002

6.611000000000001

23.583999999999996

120.94600000000001

8.592

52.659000000000006

31.069000000000003

109.705

6.336

68.576

48.227000000000004

105.17600000000002

20.468

462.27

6.005000000000001

20.561

127.565

20.799

88.545

28.095000000000002

141.767

142.192

14.081

146.65200000000002

16.432000000000002

190.85999999999999

139.588

23.452

64.398

10.946000000000002

26.709000000000003

368.71700000000004

18.086

99.256

39.93

152.26799999999997

85.572

135.745

10.386000000000001

147.549

18.764000000000003

111.983

15.076

206.573

32.007000000000005

108.355

20.934

108.39900000000002

34.408

126.798

45.617000000000004

122.37899999999999

10.109

41.536

78.106

12.044

109.006

-1.453

125.571

-4.398

86.97600000000001

30.476000000000003

173.10200000000003

215.39300000000003

8.47

95.546

248.95000000000002

121.15400000000001

87.75299999999999

37.419999999999995

134.74099999999999

5.336

139.614

5.154

89.225

12.362000000000002

94.479

19.495

94.583

29.358999999999998

89.39800000000001

39.894

86.58500000000001

99.816

94.11600000000001

83.926

103.543

12.956000000000001

96.37

12.461000000000002

138.462

2.958

122.03199999999998

5.214

119.304

18.978

139.06000000000003

6.9190000000000005

97.773

-2.3520000000000003

132.88899999999998

-1.082

126.828

-3.51

87.37

56.854000000000006

85.531

48.352000000000004

14.641999999999998

243.427

66.01299999999999

16.060000000000002

74.91900000000001

27.003000000000004

71.868

67.542

13.019000000000002

104.01100000000001

112.82300000000001

24.733

129.175

23.302999999999997

78.292

18.405

101.66400000000002

11.484

114.509

5.159000000000001

103.67999999999999

21.543

264.92900000000003

8.861

121.836

19.106

80.442

12.763000000000002

105.48499999999999

4.398000000000001

105.31500000000001

7.535

140.56400000000002

107.047

19.111

127.537

7.463

88.30900000000001

4.34

98.569

4.956

81.086

46.233000000000004

100.093

32.048

115.922

39.531

87.17499999999998

91.486

76.40799999999999

26.335

106.11400000000002

2.9410000000000003

18.735

96.551

43.296

84.43100000000001

6.631

36.778

94.17999999999999

14.306000000000001

43.553

158.68

18.753

73.92

13.798000000000002

83.901

7.331

11.715

78.881

7.865

36.658

88.442

23.583000000000002

11.307

84.072

11.363

28.270000000000003

93.37

16.542

30.488

67.42

5.088

14.915000000000001

49.391

15.281

28.607

92.473

5.712000000000001

19.163

57.681000000000004

47.609

65.09700000000001

23.92

26.329

89.916

21.195

26.825000000000003

,Proband,MappingMethod,NumLayers,Completed_Sum,Completed_Avg,Completed_Num,Failed_Sum,Failed_Avg,Failed_Num,Terminated_Sum,Terminated_Avg,Terminated_Num,All_Sum,All_Avg,All_Num
0,1,densening,6,65.216,65.216,1.0,0.000,0.000,0.0,25.868,25.868,1.0,91.084,45.542000,2.0
1,1,densening,9,75.472,75.472,1.0,0.000,0.000,0.0,16.724,16.724,1.0,92.196,46.098000,2.0
2,1,densening,12,298.498,298.498,1.0,0.000,0.000,0.0,31.782,31.782,1.0,330.280,165.140000,2.0
3,1,densening,15,112.090,112.090,1.0,0.000,0.000,0.0,6.838,6.838,1.0,118.928,59.464000,2.0
4,1,densening,18,88.586,88.586,1.0,0.000,0.000,0.0,34.726,34.726,1.0,123.312,61.656000,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,24,widening,9,49.391,49.391,1.0,15.281,15.281,1.0,28.607,28.607,1.0,93.279,31.093000,3.0
410,24,widening,12,92.473,92.473,1.0,5.712,5.712,1.0,19.163,19.163,1.0,117.348,39.116000,3.0
411,24,widening,15,57.681,57.681,1.0,0.000,0.000,0.0,47.609,47.609,1.0,105.290,52.645000,2.0
412,24,widening,18,65.097,65.097,1.0,23.920,23.920,1.0,26.329,26.329,1.0,115.346,38.448667,3.0
413,24,widening,21,89.916,89.916,1.0,21.195,21.195,1.0,26.825,26.825,1.0,137.936,45.978667,3.0

* Plot: über alle Probanden für eine bestimmte Konstellation aus mapping method, Ebenenanzahl, Zielebene 
    * Y: Ebenen / Tiefe
    * X: Zeit
* Bonus: Y-Achse nach realen Tiefenwerten  skaliert (depthlayers.csv)

| PROBAND | TIMESTAMP | CURRENT_LAYER | Z     |
| ---     | ---       | ---           | ---   |
| 154     | 12345678  | 6             | -0.54 |
| .       | .         | .             | .     |
| .       | .         | .             | .     |

### Bonus
---
* depthlayers.csv: Mapping der Tiefenwerte auf die zugehörige Ebene nach Mapping-Methode Achtung: Z-Werte in Studie sind im Bereich [–1,0] zu bewerten, depthlayers.csv gibt die absolut-Werte an!
* Für erfolgreiche Trials: Jeweils zwischen HOLD und COMPLETED 
    * Maximale Schwankung (% der Ebenenbreite)
    * Durchschnittstiefe (prozentualer Abstand zur Ebenenmitte) 
    * Wie „weit“ waren die Probanden von einem Fehlschlag entfernt / wie sicher haben Sie die ebene gehalten ?
* „Wackler“ vor HOLD (wie oft wurde die Zielebene erreicht, aber nicht gehalten ?)
* Dies jeweils nach Ebenenanzahl und Mapping_Method gruppiert (über alle Probanden)
* Statistische Auswertung – Vorschläge?
* Hypothesen:
    * Sweet Spot für Anzahl der Ebenen (bspw: ab wann nimmt die Fehlerquote plötzlich stark zu ? Oder: bei welcher Ebenenanzahl wird eine Genauigkeit > 95% im Schnitt erzielt ?)
    * Vergleich der Mapping_Method: 
        * H1: widening ist genauer als direct und densening - mit zunehmender Tiefe nimmt die benötigte Kraft zu  Genauigkeit sinkt, deswegen sind die „unteren“ (aka höheren) Ebenen weiter auseinander
        * H2: densening ist genauer als direct und widening - mit zunehmender Tiefe nimmt die benötigte Kraft zu  konstante Kraftnutzung für den Ebenenwechsel = „untere“ (aka höhere) Ebenen näher beieinander
        * H3: direct ist genauer als widening und densening - Kraft spielt keine (oder nur geringfügige) Rolle, wichtig ist die äquidistante Positionierung der Tiefenebenen

In [ ]:
# your code here

In [ ]:
print(test)